In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [ ]:
data = pd.read_csv('50_Startups.csv')

In [ ]:
data.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
list(data.columns)

['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit']

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [ ]:
data.shape

(50, 5)

In [ ]:
data.State.value_counts()

State
New York      17
California    17
Florida       16
Name: count, dtype: int64

In [ ]:
data.State.value_counts(normalize=True)*100

State
New York      34.0
California    34.0
Florida       32.0
Name: proportion, dtype: float64

In [ ]:
data [['State', 'Profit']]. sort_values('Profit', ascending = False)[0:10]

State     Profit
0    New York  192261.83
1  California  191792.06
2     Florida  191050.39
3    New York  182901.99
4     Florida  166187.94
5    New York  156991.12
6  California  156122.51
7     Florida  155752.60
8    New York  152211.77
9  California  149759.96

In [ ]:
data [['State', 'Profit']]. sort_values('Profit')[0:5]

State    Profit
49  California  14681.40
48    New York  35673.41
47  California  42559.73
46     Florida  49490.75
45    New York  64926.08

In [ ]:
data['Cost'] = data['R&D Spend'] + data['Administration'] + data['Marketing Spend']

In [ ]:
data.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit  \
0  165349.20       136897.80        471784.10    New York  192261.83   
1  162597.70       151377.59        443898.53  California  191792.06   
2  153441.51       101145.55        407934.54     Florida  191050.39   
3  144372.41       118671.85        383199.62    New York  182901.99   
4  142107.34        91391.77        366168.42     Florida  166187.94   

        Cost  
0  774031.10  
1  757873.82  
2  662521.60  
3  646243.88  
4  599667.53

In [ ]:
data [['State', 'Profit', 'Cost']]. sort_values('Cost', ascending = True)[0:10]

State     Profit       Cost
48    New York   35673.41   52285.20
45    New York   64926.08  127057.20
47  California   42559.73  135426.92
49  California   14681.40  162156.86
43    New York   69758.98  178422.20
44  California   65200.33  205318.60
32  California   97427.84  238713.72
19    New York  122776.86  239933.81
42  California   71498.49  267831.67
30     Florida   99937.59  268767.00

In [ ]:
data [['State', 'Profit', 'Cost']]. sort_values('Profit', ascending = False)[0:10]

State     Profit       Cost
0    New York  192261.83  774031.10
1  California  191792.06  757873.82
2     Florida  191050.39  662521.60
3    New York  182901.99  646243.88
4     Florida  166187.94  599667.53
5    New York  156991.12  594552.97
6  California  156122.51  409531.15
7     Florida  155752.60  599704.87
8    New York  152211.77  580874.76
9  California  149759.96  536995.67

In [ ]:
data.groupby('State').agg( { "Profit" :["mean"],
                             "Cost" : ["mean"]})

Profit           Cost
                     mean           mean
State                                   
California  103905.175294  367945.110588
Florida     118774.024375  449816.465000
New York    113756.446471  403084.548824

SIMPLE LINEAR REGRESSION

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['State_Label'] = le.fit_transform(data['State'])
data.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit  \
0  165349.20       136897.80        471784.10    New York  192261.83   
1  162597.70       151377.59        443898.53  California  191792.06   
2  153441.51       101145.55        407934.54     Florida  191050.39   
3  144372.41       118671.85        383199.62    New York  182901.99   
4  142107.34        91391.77        366168.42     Florida  166187.94   

        Cost  State_Label  
0  774031.10            2  
1  757873.82            0  
2  662521.60            1  
3  646243.88            2  
4  599667.53            1

In [ ]:
data.isna().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
Cost               0
State_Label        0
dtype: int64

In [ ]:
from sklearn.preprocessing import MinMaxScaler
data_new = data
data_new.drop(['State'], axis = 1, inplace = True)
data_new.head(5)
scaler = MinMaxScaler()
data_normalised = scaler.fit_transform(data)
print(data_normalised)

[[1.         0.65174393 1.         1.         1.         1.        ]
 [0.98335946 0.76197173 0.94089337 0.99735461 0.97761362 0.        ]
 [0.92798459 0.37957895 0.8646636  0.99317808 0.84550033 0.5       ]
 [0.87313643 0.51299839 0.81223513 0.94729239 0.82294708 1.        ]
 [0.85943772 0.30532804 0.77613557 0.85317138 0.75841419 0.5       ]
 [0.797566   0.3694479  0.76912588 0.80138177 0.75132781 1.        ]
 [0.81412828 0.73016111 0.27071031 0.79649041 0.49497469 0.        ]
 [0.7880179  0.71745725 0.68649342 0.79440736 0.75846592 0.5       ]
 [0.72901786 0.74173276 0.66049977 0.77446805 0.73237626 1.        ]
 [0.74590551 0.43692884 0.64644319 0.7606613  0.6715805  0.        ]
 [0.61635061 0.45150637 0.48573267 0.74017475 0.53950142 0.5       ]
 [0.60884455 0.30836422 0.52936195 0.72968626 0.5402482  0.        ]
 [0.56766982 0.57883556 0.52956308 0.71462897 0.58017423 0.5       ]
 [0.55635219 0.64106561 0.53555202 0.67364377 0.59282247 0.        ]
 [0.72539353 0.8013272  0.54370828

In [ ]:
data_new.head(5)

R&D Spend  Administration  Marketing Spend     Profit       Cost  \
0  165349.20       136897.80        471784.10  192261.83  774031.10   
1  162597.70       151377.59        443898.53  191792.06  757873.82   
2  153441.51       101145.55        407934.54  191050.39  662521.60   
3  144372.41       118671.85        383199.62  182901.99  646243.88   
4  142107.34        91391.77        366168.42  166187.94  599667.53   

   State_Label  
0            2  
1            0  
2            1  
3            2  
4            1

In [ ]:
X = data[["R&D Spend"]]
y = data["Profit"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(X_train.values,y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
r2_score( y_test, y_pred)

0.9265108109341951

In [ ]:
print(lr.intercept_)

49336.6680379911


In [ ]:
lr.predict(X[0:1])

array([190480.25107829])

In [ ]:
type(lr)

sklearn.linear_model._base.LinearRegression

In [ ]:
X[0:5]

R&D Spend
0  165349.20
1  162597.70
2  153441.51
3  144372.41
4  142107.34

In [ ]:
predictions = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(predictions.head())

       Actual      Predicted
13  134307.35  127862.209964
39   81005.76   82250.563346
30   99937.59  102255.720782
45   64926.08   50190.473476
17  125370.37  130136.881905


In [ ]:
X = data[["Administration"]]
y = data["Profit"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

lr.fit(X_train.values,y_train)
y_pred = lr.predict(X_test)

r2_score( y_test, y_pred)

-0.19108803250893636

In [ ]:
print(lr.intercept_)

98921.07066056214


In [ ]:
lr.predict(X[0:5])

array([117827.57467744, 119827.33075678, 112889.94925002, 115310.44878582,
       111542.88683741])

In [ ]:
predictions = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(predictions.head())

       Actual      Predicted
13  134307.35  117633.848260
39   81005.76  110381.453646
30   99937.59  114891.906750
45   64926.08  116067.437874
17  125370.37  118957.257137


In [ ]:
X = data[["Marketing Spend"]]
y = data["Profit"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

lr.fit(X_train.values,y_train)
y_pred = lr.predict(X_test)

r2_score( y_test, y_pred)

-0.11205578997827947

In [ ]:
print(lr.intercept_)

48923.31296724075


In [ ]:
lr.predict(X[0:5])

array([182462.19522503, 174569.16142223, 164389.52411328, 157388.28441585,
       152567.58907765])

In [ ]:
predictions = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(predictions.head())

       Actual      Predicted
13  134307.35  120440.331743
39   81005.76   98457.010516
30   99937.59   74718.086315
45   64926.08   49462.221939
17  125370.37  128906.206651


In [ ]:
X = data_new[["State_Label"]]
y = data_new["Profit"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

lr.fit(X_train.values,y_train)
y_pred = lr.predict(X_test)

r2_score( y_test, y_pred)

-0.6542302152837494

In [ ]:
print(lr.intercept_)

106464.4058846154


In [ ]:
predictions = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(predictions.head())

       Actual      Predicted
13  134307.35  106464.405885
39   81005.76  106464.405885
30   99937.59  115651.720500
45   64926.08  124839.035115
17  125370.37  124839.035115


MULTIPLE REGRESSION

In [ ]:
data_new.drop(['Cost'], axis = 1, inplace = True)
data_new.head(5)

R&D Spend  Administration  Marketing Spend     Profit  State_Label
0  165349.20       136897.80        471784.10  192261.83            2
1  162597.70       151377.59        443898.53  191792.06            0
2  153441.51       101145.55        407934.54  191050.39            1
3  144372.41       118671.85        383199.62  182901.99            2
4  142107.34        91391.77        366168.42  166187.94            1

In [ ]:
X = data_new.drop(columns=['Profit'])
y = data_new['Profit']

In [ ]:
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (50, 4)
Shape of y: (50,)


In [ ]:
X = X.values
y = y.values

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print("Shape of X:", X_train.shape)
print("Shape of y:", y_train.shape)

Shape of X: (40, 4)
Shape of y: (40,)


In [ ]:
model_multiple = LinearRegression()

# Train the model
model_multiple.fit(X_train, y_train)

y_pred_multiple = model_multiple.predict(X_test)

mse_multiple = mean_squared_error(y_test, y_pred_multiple)
r2_multiple = r2_score(y_test, y_pred_multiple)

print("\nMultiple Linear Regression")
print(f"  Mean Squared Error: {mse_multiple:.4f}")
print(f"  R² Score: {r2_multiple:.4f}")


Multiple Linear Regression
  Mean Squared Error: 80929465.4910
  R² Score: 0.9001


In [ ]:
print(model_multiple.intercept_)

54080.71684611377


In [ ]:
predictions = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred_multiple})
print(predictions.head())

      Actual      Predicted
0  134307.35  126720.661507
1   81005.76   84909.089619
2   99937.59   98890.318549
3   64926.08   46479.312402
4  125370.37  129113.183188
